version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: placement_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: placement_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: placement_fastapi_backend
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/placement_db
      - JWT_SECRET=super_secret_placement_ai_key_2026
    depends_on:
      - db

volumes:
  postgres_data:
